[default]
DATABASE_URL = "sqlite:///oraculo_analista.db"

# Conta oraculosia
groq_api_key = "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"
# Conta flashdigita
# groq_api_key = "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"
# Conta do gmail programador.descpro
# groq_api_key = "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"
